// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rental.DbModels;

namespace Rental.Migrations
{
    [DbContext(typeof(zavrsniContext))]
    partial class zavrsniContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rental.DbModels.Kategorija", b =>
                {
                    b.Property<int>("Idkategorija")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDKategorija")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Idkategorija")
                        .HasName("PK__Kategori__7E48B6E5F7D0FE93");

                    b.ToTable("Kategorija");
                });

            modelBuilder.Entity("Rental.DbModels.Klijent", b =>
                {
                    b.Property<int>("Idklijent")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDKlijent")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("EMail")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Idklijent")
                        .HasName("PK__Klijent__0769C703201E9FEA");

                    b.ToTable("Klijent");
                });

            modelBuilder.Entity("Rental.DbModels.Mjesto", b =>
                {
                    b.Property<int>("Idmjesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDMjesto")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Idmjesto")
                        .HasName("PK__Mjesto__2CC2E480547B6EB9");

                    b.ToTable("Mjesto");
                });

            modelBuilder.Entity("Rental.DbModels.NacinPlacanja", b =>
                {
                    b.Property<int>("IdnacinPlacanja")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDNacinPlacanja")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("IdnacinPlacanja")
                        .HasName("PK__NacinPla__D431C3C9F34CB413");

                    b.ToTable("NacinPlacanja");
                });

            modelBuilder.Entity("Rental.DbModels.Rezervacija", b =>
                {
                    b.Property<int>("Idrezervacija")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDRezervacija")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumDo")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("datetime");

                    b.Property<int>("Klijent")
                        .HasColumnType("int");

                    b.Property<int>("MjestoPovrata")
                        .HasColumnType("int");

                    b.Property<int>("MjestoPreuzimanja")
                        .HasColumnType("int");

                    b.Property<int>("Nacin")
                        .HasColumnType("int");

                    b.Property<int>("Vozilo")
                        .HasColumnType("int");

                    b.HasKey("Idrezervacija")
                        .HasName("PK__Rezervac__21D11B290805B468");

                    b.HasIndex("Klijent");

                    b.HasIndex("MjestoPovrata");

                    b.HasIndex("MjestoPreuzimanja");

                    b.HasIndex("Nacin");

                    b.HasIndex("Vozilo");

                    b.ToTable("Rezervacija");
                });

            modelBuilder.Entity("Rental.DbModels.Vozilo", b =>
                {
                    b.Property<int>("Idvozilo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDVozilo")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cijena")
                        .HasColumnType("int");

                    b.Property<bool>("Dostupan")
                        .HasColumnType("bit");

                    b.Property<int>("Kategorija")
                        .HasColumnName("kategorija")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Registracija")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Idvozilo")
                        .HasName("PK__Vozilo__2A0736848F114D28");

                    b.HasIndex("Kategorija");

                    b.ToTable("Vozilo");
                });

            modelBuilder.Entity("Rental.DbModels.Rezervacija", b =>
                {
                    b.HasOne("Rental.DbModels.Klijent", "KlijentNavigation")
                        .WithMany("Rezervacija")
                        .HasForeignKey("Klijent")
                        .HasConstraintName("FK__Rezervaci__Klije__30F848ED")
                        .IsRequired();

                    b.HasOne("Rental.DbModels.Mjesto", "MjestoPovrataNavigation")
                        .WithMany("RezervacijaMjestoPovrataNavigation")
                        .HasForeignKey("MjestoPovrata")
                        .HasConstraintName("FK__Rezervaci__Mjest__2F10007B")
                        .IsRequired();

                    b.HasOne("Rental.DbModels.Mjesto", "MjestoPreuzimanjaNavigation")
                        .WithMany("RezervacijaMjestoPreuzimanjaNavigation")
                        .HasForeignKey("MjestoPreuzimanja")
                        .HasConstraintName("FK__Rezervaci__Mjest__2E1BDC42")
                        .IsRequired();

                    b.HasOne("Rental.DbModels.NacinPlacanja", "NacinNavigation")
                        .WithMany("Rezervacija")
                        .HasForeignKey("Nacin")
                        .HasConstraintName("FK__Rezervaci__Nacin__31EC6D26")
                        .IsRequired();

                    b.HasOne("Rental.DbModels.Vozilo", "VoziloNavigation")
                        .WithMany("Rezervacija")
                        .HasForeignKey("Vozilo")
                        .HasConstraintName("FK__Rezervaci__Vozil__300424B4")
                        .IsRequired();
                });

            modelBuilder.Entity("Rental.DbModels.Vozilo", b =>
                {
                    b.HasOne("Rental.DbModels.Kategorija", "KategorijaNavigation")
                        .WithMany("Vozilo")
                        .HasForeignKey("Kategorija")
                        .HasConstraintName("FK__Vozilo__kategori__2B3F6F97")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
